stickers = {
    'привет': 'AAMCAQADGQEAA8hiC2Xxi-ocI2pwCJphsum-SXJtRAACUgEAAiAqAAFERe6IQ2kd5rEBAAdtAAMjBA',
    'пока': 'AAMCBAADGQEAA8piC2a2QZlREw9pJufQX6yuWkpxtQACGAAD4YLkFJK0RM9MsjF_AQAHbQADIwQ'
}
